### ISSUE TITLE
Problem adding jQuery to app

### ISSUE THREAD

**Issue by Aktionarius** [Aktionarius/umbracowebapp#14]
I have tried to add jquery. It seems to work but not sure if it is correct.

What I have done:
npm install --save jquery
and
npm install -D @types/jquery

On page.component.ts line 7 added:
import * as $ from 'jquery';

And onInit line 53-57 my jquery code is.

Got two issues:

1) jquery seems to work out okay but  .carousel from materilizecss is not working
http://materializecss.com/carousel.html

carousell html is added on side-1 between cards and image/text 50/50 (Bottom)
![image](https://cloud.githubusercontent.com/assets/1810657/22487800/2595efa2-e80f-11e6-9b47-c373bb2c834d.png)

2) What will I do when I as an example also would like to use jQuery on menu.component?

**Comment by webcat12345** [comment]
Let me know , if `materializecss` was working before `jquery` injected.

**Comment by Aktionarius** [comment]
I have not seen any materializecss js working at all
Css is okay.

**Comment by webcat12345** [comment]
Ok got it.

**Comment by webcat12345** [comment]
I implemented **Materialize css** to Angular2 and you can see how it works.

Please follow below steps: 

`git pull`
`npm install`

Currently I commented your some code in order to show materialize components.
Please check the sample components and try to change the Backend String.

Also if possible, let me know the times.

**Comment by Aktionarius** [comment]
This is not working on my side.... Are you able on looking at it now?

**Comment by Aktionarius** [comment]
Would like to know if and when you will look as this issue?

**Comment by webcat12345** [comment]
We 'v already succeed to using materialized css in app through Teamviewer, isn't it?
Regarding to the lazyloader I will let you know if I find out solution. Still I didn't got what the issue is.

**Comment by Aktionarius** [comment]
NO. We made the static html working.
You told me to add attribute: materialize="carousel"

Now the html is same as added static on top of pages:

![image](https://cloud.githubusercontent.com/assets/1810657/22630637/3dfe8db8-ebfe-11e6-88d1-5c184fe9b52d.png)


It seems like inline/json html is not initilized and fired before after materilize maby??

**Comment by webcat12345** [comment]
I tried some ways but all are not working for this case.
Now I am trying to create component DOM-Tree after getting response from backend API.
I will try that today and will let you know.

**Comment by Aktionarius** [comment]
Closed. Issue solved
